kbd_layout = ""

net_wireless = "直"
net_wired = ""

update = ""

bat_charging = ""
bat_not_available = ""
bat_empty = ""
bat_quarter = ""
bat_half = ""
bat_three_quarters = ""
bat_full = ""
bat_10 = ""
bat_20 = ""
bat_30 = ""
bat_40 = ""
bat_50 = ""
bat_60 = ""
bat_70 = ""
bat_80 = ""
bat_90 = ""

disk_drive = ""

cpu = ""
cpu_boost_on = ""
cpu_boost_off = ""

cogs = "" #""

memory_mem = ""
memory_swap = "" #""

thermometer = ""

date = ""
time = ""
