kbd_layout = "􀇳"

net_wireless = "􀙇"
net_wired = "􀩲"
net_vpn = "􀙨"

update = "􀯛"

bat = [
  "󰁻",
  "󰁽",
  "󰂀",
  "󰁹"
]
bat_charging = [
  "󰂆",
  "󰂈",
  "󰂊",
  "󰂅"
]
bat_not_available = "󰂑"

disk_drive = "􀤂"

cpu = "􀍾"
cpu_boost_on = ""
cpu_boost_off = ""

cogs = "" #""

memory_mem = "􀫦"
memory_swap = "􀥾"

thermometer = "􀇬"

date = "􀉉"
time = "􀐫"
