kbd_layout = ""

net_wireless = "直"
net_wired = ""

update = ""

bat_charging = ""
bat_not_available = ""
bat_empty = ""
bat_quarter = ""
bat_half = ""
bat_three_quarters = ""
bat_full = ""
bat = ""

disk_drive = ""

cpu = ""
cpu_boost_on = ""
cpu_boost_off = ""

cogs = "" #""

memory_mem = ""
memory_swap = "" #""

thermometer = ""

date = ""
time = ""
