icons_format = "{icon}"

[theme]
theme = "archw"

[icons]
icons = "archw.toml"

#
# Network
[[block]]
block = "net"
#on_click = "alacritty -e nmtui"
#interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
#interface_name_include = []
#ap_format = "{ssid}"
format = " $icon $ip "

#
# Battery
[[block]]
block = "battery"
format = " $icon $percentage {$time |}"
full_format = " $icon $percentage {$time |}"

#device = "DisplayDevice"
driver = "upower"
missing_format = ""
interval = 30

#
# Package updates
[[block]]
block = "custom"
command = "archw --status json sysupd"
interval = 5
json = true
[[block.click]]
button = "left"
cmd = "archw --status json sysupd run"

#
# Keyboard layout
[[block]]
block = "custom"
command = "echo '{\"icon\":\"kbd_layout\",\"text\": \"'$(archw --lang get | tr '[:lower:]' '[:upper:]')'\"}'"
interval = 30
json = true
[[block.click]]
button = "left"
cmd = "archw --lang cycle"

#
# Disk
[[block]]
block = "disk_space"
path = "/"
info_type = "used"
alert = 90
warning = 80
format = " $icon $percentage.eng(w:2) "

#
# CPU usage
[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization "

#
# Memory usage
[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

#
# Temps
[[block]]
block = "temperature"
interval = 10
format = " $icon $average.eng(w:2) "
chip = "*-isa-*"
inputs = ["Package id 0", "Package id 1", "Package id 2", "Package id 3"]
good = 25
idle = 45
info = 75
warning = 92

#
# Time
[[block]]
block = "custom"
command = "echo '{\"icon\":\"date\",\"text\": \"'$(date +\"%b %d\")'\"}'"
interval = 10
json = true

[[block]]
block = "custom"
command = "archw --status json time"
interval = 1
json = true
[[block.click]]
button = "left"
cmd = "archw --status json time sectoggle"
